@startuml

'========================
' CLASES BÁSICAS
'========================

class Juego
class Nivel
class Personaje
class Jugador
class Enemigo
class Arma
class Proyectil
class Vehiculo
class Item
class SistemaColisiones

'========================
' HERENCIA (es un)
'========================

Jugador --|> Personaje
Enemigo --|> Personaje

'========================
' COMPOSICIÓN (tiene un fuerte)
'========================

Juego *-- Nivel

'========================
' AGREGACIÓN (tiene un débil)
'========================

Jugador o-- Arma
Jugador o-- Vehiculo
Nivel o-- Enemigo
Nivel o-- Item

'========================
' DEPENDENCIAS (usa un)
'========================

Arma ..> Proyectil
SistemaColisiones ..> Personaje
SistemaColisiones ..> Proyectil
Juego ..> SistemaColisiones

@enduml